/**
 * 코인이지 Figma 배너 모듈
  * 
   * Figma REST API를 사용하여:
    * 1. 피그마 템플릿의 현재 배너 프레임을 PNG로 Export
     * 2. 텔레그램에 배너 이미지와 함께 브리핑 발송
      * 3. X 포스팅에 배너 이미지 첨부
       * 
        * 환경변수:
         *   FIGMA_TOKEN       - Figma Personal Access Token
          *   FIGMA_FILE_KEY    - Figma 파일 키 (기본: SRPoM0lDRtn61Q91sFWg1D)
           *   FIGMA_FRAME_ID    - Export할 프레임 노드 ID (기본: 28334:14)
            */

            import { writeFile, mkdir } from 'fs/promises';
            import { existsSync } from 'fs';

            // ============================================================
            // 설정
            // ============================================================
            const FIGMA_CONFIG = {
              token: process.env.FIGMA_TOKEN || '',
                fileKey: process.env.FIGMA_FILE_KEY || 'SRPoM0lDRtn61Q91sFWg1D',
                  frameId: process.env.FIGMA_FRAME_ID || '28334:14',
                    scale: 2,  // 2x for high-res
                    };

                    const FIGMA_API = 'https://api.figma.com/v1';

                    // ============================================================
                    // Figma REST API: 프레임을 PNG로 Export
                    // ============================================================
                    export async function exportFigmaBanner() {
                      if (!FIGMA_CONFIG.token) {
                          console.log('  ⚠️ FIGMA_TOKEN 미설정 — 배너 Export 스킵');
                              return null;
                                }

                                  try {
                                      console.log('  🎨 Figma API: 배너 이미지 요청 중...');

                                          // Step 1: Figma Images API로 PNG URL 가져오기
                                              const nodeId = FIGMA_CONFIG.frameId;
                                                  const imageUrl = `${FIGMA_API}/images/${FIGMA_CONFIG.fileKey}?ids=${encodeURIComponent(nodeId)}&format=png&scale=${FIGMA_CONFIG.scale}`;

                                                      const imageRes = await fetch(imageUrl, {
                                                            headers: {
                                                                    'X-Figma-Token': FIGMA_CONFIG.token,
                                                                          },
                                                                              });

                                                                                  if (!imageRes.ok) {
                                                                                        const errText = await imageRes.text();
                                                                                              throw new Error(`Figma API ${imageRes.status}: ${errText}`);
                                                                                                  }

                                                                                                      const imageData = await imageRes.json();
                                                                                                      
                                                                                                          if (imageData.err) {
                                                                                                                throw new Error(`Figma API error: ${imageData.err}`);
                                                                                                                    }
                                                                                                                    
                                                                                                                        // 노드 ID에 해당하는 이미지 URL 추출
                                                                                                                            const images = imageData.images || {};
                                                                                                                                const pngUrl = images[nodeId];
                                                                                                                                
                                                                                                                                    if (!pngUrl) {
                                                                                                                                          throw new Error('Figma에서 이미지 URL을 받지 못함');
                                                                                                                                              }
                                                                                                                                              
                                                                                                                                                  console.log('  📥 PNG 다운로드 중...');
                                                                                                                                                  
                                                                                                                                                      // Step 2: PNG 이미지 다운로드
                                                                                                                                                          const pngRes = await fetch(pngUrl);
                                                                                                                                                              if (!pngRes.ok) {
                                                                                                                                                                    throw new Error(`PNG 다운로드 실패: ${pngRes.status}`);
                                                                                                                                                                        }
                                                                                                                                                                        
                                                                                                                                                                            const pngBuffer = Buffer.from(await pngRes.arrayBuffer());
                                                                                                                                                                            
                                                                                                                                                                                // Step 3: 로컬에 저장
                                                                                                                                                                                    const bannersDir = './banners';
                                                                                                                                                                                        if (!existsSync(bannersDir)) await mkdir(bannersDir, { recursive: true });
                                                                                                                                                                                        
                                                                                                                                                                                            const dateStr = new Date().toISOString().split('T')[0];
                                                                                                                                                                                                const filename = `${bannersDir}/banner_${dateStr}.png`;
                                                                                                                                                                                                    await writeFile(filename, pngBuffer);
                                                                                                                                                                                                    
                                                                                                                                                                                                        console.log(`  ✅ 배너 저장: ${filename} (${(pngBuffer.length / 1024).toFixed(1)}KB)`);
                                                                                                                                                                                                        
                                                                                                                                                                                                            return {
                                                                                                                                                                                                                  buffer: pngBuffer,
                                                                                                                                                                                                                        filename,
                                                                                                                                                                                                                              size: pngBuffer.length,
                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                        console.error(`  ❌ Figma 배너 Export 에러: ${err.message}`);
                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              // ============================================================
                                                                                                                                                                                                                                              // 텔레그램: 이미지 + 캡션 발송
                                                                                                                                                                                                                                              // ============================================================
                                                                                                                                                                                                                                              export async function sendTelegramPhoto(imageBuffer, caption, chatId, botToken) {
                                                                                                                                                                                                                                                if (!botToken || !chatId || !imageBuffer) {
                                                                                                                                                                                                                                                    console.error('[텔레그램] 필수 파라미터 누락 (botToken/chatId/imageBuffer)');
                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                const url = `https://api.telegram.org/bot${botToken}/sendPhoto`;
                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                    // FormData로 이미지 + 캡션 전송
                                                                                                                                                                                                                                                                        const formData = new FormData();
                                                                                                                                                                                                                                                                            const blob = new Blob([imageBuffer], { type: 'image/png' });
                                                                                                                                                                                                                                                                                formData.append('chat_id', chatId);
                                                                                                                                                                                                                                                                                    formData.append('photo', blob, 'coineasy_daily_banner.png');
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                        // 캡션 길이 제한 (1024자)
                                                                                                                                                                                                                                                                                            if (caption) {
                                                                                                                                                                                                                                                                                                  const trimmedCaption = caption.length > 1020 ? caption.substring(0, 1020) + '...' : caption;
                                                                                                                                                                                                                                                                                                        formData.append('caption', trimmedCaption);
                                                                                                                                                                                                                                                                                                              formData.append('parse_mode', 'Markdown');
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                      const res = await fetch(url, {
                                                                                                                                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                                                                                                                                  body: formData,
                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                          const result = await res.json();
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                              if (!result.ok) {
                                                                                                                                                                                                                                                                                                                                                    // Markdown 실패시 일반 텍스트로 재시도
                                                                                                                                                                                                                                                                                                                                                          console.warn(`[텔레그램] Markdown 캡션 실패, 일반 텍스트로 재시도`);
                                                                                                                                                                                                                                                                                                                                                                const formData2 = new FormData();
                                                                                                                                                                                                                                                                                                                                                                      const blob2 = new Blob([imageBuffer], { type: 'image/png' });
                                                                                                                                                                                                                                                                                                                                                                            formData2.append('chat_id', chatId);
                                                                                                                                                                                                                                                                                                                                                                                  formData2.append('photo', blob2, 'coineasy_daily_banner.png');
                                                                                                                                                                                                                                                                                                                                                                                        if (caption) {
                                                                                                                                                                                                                                                                                                                                                                                                formData2.append('caption', caption.replace(/\*([^*]+)\*/g, '$1').replace(/_([^_]+)_/g, '$1'));
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                            const res2 = await fetch(url, { method: 'POST', body: formData2 });
                                                                                                                                                                                                                                                                                                                                                                                                                  const result2 = await res2.json();
                                                                                                                                                                                                                                                                                                                                                                                                                        if (!result2.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(`[텔레그램] 사진 발송 실패: ${result2.description}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                        return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`[텔레그램] 📸 배너 이미지 발송 완료 → ${chatId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(`[텔레그램 사진 에러] ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // X (Twitter): 이미지 첨부 포스팅용 미디어 업로드
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export async function uploadMediaToX(imageBuffer) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const apiKey = process.env.X_API_KEY;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const apiSecret = process.env.X_API_SECRET;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const accessToken = process.env.X_ACCESS_TOKEN;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const accessSecret = process.env.X_ACCESS_TOKEN_SECRET;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!apiKey || !accessToken) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('  ⚠️ X API 키 미설정 — 미디어 업로드 스킵');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Twitter API v1.1 media/upload (base64)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { TwitterApi } = await import('twitter-api-v2');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const client = new TwitterApi({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              appKey: apiKey,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    appSecret: apiSecret,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          accessToken: accessToken,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                accessSecret: accessSecret,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const mediaId = await client.v1.uploadMedia(imageBuffer, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              mimeType: 'image/png',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`  ✅ X 미디어 업로드 완료: ${mediaId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return mediaId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(`  ❌ X 미디어 업로드 에러: ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
